import type { Metadata } from "next";
import localFont from "next/font/local";
import { Headbar } from "@/components/public/head-bar";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Headbar></Headbar>
        <div className="pt-28 px-[5%] md:px-[10%] xl:px-[10%] 2xl:px-[10%] flex flex-col items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}
